version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.12.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false 
      - ES_JAVA_OPTS=-Xms1g -Xmx1g 
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - elk

  kibana:
    image: kibana:8.12.0
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.0
    volumes:
      - ./logstash_config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logs:/logs
    ports:
      - "5044:5044"
    depends_on:
      - elasticsearch
    networks:
      - elk

  go-app:
    build: ./go-lang-server
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - elk
    volumes:
      - ./logs/golang:/app/logs/golang

  node-app:
    build: ./nodejs-server
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - elk
    volumes:
      - ./logs/nodejs:/app/logs/nodejs

volumes:
  es_data:
    driver: local

networks:
  elk:
    driver: bridge
